# Generated by Django 5.0.3 on 2024-12-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zlauth', '0002_alter_captchamodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captchamodel',
            old_name='captcah',
            new_name='captcha',
        ),
    ]
